### ISSUE TITLE
segfault when run localizer.py

### ISSUE THREAD

**Issue by jinyixin621** [anlthms/whale-2015#2]
./run.sh: line 58: 13907 Segmentation fault      ./localizer.py -z 32 -e $num_epochs -w $data_dir/macrotrain -tw $data_dir/macrotest -r 0 -s model1.pkl -bgpu -pn 1 -iw $imwidth --serialize 1 ${@:2}

**Comment by jinyixin621** [comment]
I think it has something to do with GPU

**Comment by anlthms** [comment]
Hard to troubleshoot this without more details on your environment.
Can you try this command from the neon directory and see if it works?
python examples/cifar10_conv.py -e1 -r0 -bgpu

**Comment by jinyixin621** [comment]
I am using K20, it seems like there is some issue for supporting K20? Is it possible you release some trained model? Or sample results from your model?
